import { ChibiConfig } from './types';

export const SKIN_COLORS = [
  { name: 'Chiara', value: '#ffeee4' },
  { name: 'Pesca', value: '#ffd6ba' },
  { name: 'Miele', value: '#fcd5a1' },
  { name: 'Dorata', value: '#e0a96d' },
  { name: 'Ambrata', value: '#b07d62' },
  { name: 'Cacao', value: '#8c593b' },
  { name: 'Cioccolato', value: '#583110' },
  { name: 'Fantasia Rosa', value: '#ffccd5' },
  { name: 'Fantasia Lilla', value: '#e2afff' },
  { name: 'Fantasia Verde', value: '#c7f9cc' },
];

export const HAIR_COLORS = [
  { name: 'Bionda', value: '#ffd166' },
  { name: 'Castana', value: '#6f4e37' },
  { name: 'Mora', value: '#1a1a1a' },
  { name: 'Rossa', value: '#e2583e' },
  { name: 'Rosa Pastello', value: '#ff85a1' },
  { name: 'Azzurro Cielo', value: '#4ea8de' },
  { name: 'Menta', value: '#70e000' },
  { name: 'Lavanda', value: '#b5179e' },
  { name: 'Ghiaccio', value: '#e9ecef' },
  { name: 'Neon Arancione', value: '#f77f00' },
];

export const EYE_COLORS = [
  { name: 'Nero Carbone', value: '#212529' },
  { name: 'Blu Oceano', value: '#0077b6' },
  { name: 'Verde Smeraldo', value: '#2b9348' },
  { name: 'Castano Nocciola', value: '#9c6644' },
  { name: 'Rubino Red', value: '#d90429' },
  { name: 'Viola Regale', value: '#7209b7' },
  { name: 'Giallo Ambra', value: '#ffb703' },
  { name: 'Fucsia Pop', value: '#ff007f' },
  { name: 'Turchese Acqua', value: '#00f5d4' },
];

export const CLOTHES_COLORS = [
  { name: 'Rosso Scuro', value: '#c1121f' },
  { name: 'Blu Marina', value: '#003049' },
  { name: 'Verde Oliva', value: '#606c38' },
  { name: 'Bianco Candido', value: '#fdf0d5' },
  { name: 'Giallo Sole', value: '#fca311' },
  { name: 'Rosa Bubblegum', value: '#ff85a1' },
  { name: 'Nero Gotico', value: '#1b1b1e' },
  { name: 'Lilla', value: '#dec9e9' },
  { name: 'Arancione Zucca', value: '#f77f00' },
  { name: 'Grigio Fumo', value: '#4a4e69' },
];

export const BG_COLORS = [
  { name: 'Pesca Chiaro', value: '#ffe5d9' },
  { name: 'Rosa Incanto', value: '#fec5bb' },
  { name: 'Limone Soft', value: '#f9bec7' }, // pinkish-yellow
  { name: 'Azzurro Sogno', value: '#d8e2dc' },
  { name: 'Lavanda Soft', value: '#ece4db' },
  { name: 'Menta Chiara', value: '#d8f3dc' },
  { name: 'Spazio Profondo', value: '#2b2d42' },
  { name: 'Glicine', value: '#ebd9fc' },
  { name: 'Nuvola', value: '#f4f6f9' },
];

export const DEFAULT_CHIBI: ChibiConfig = {
  id: 'template_default',
  name: 'Chibi Base',
  gender: 'base',
  armPose: 'neutral',
  skinColor: '#ffeee4',
  faceShape: 'round',
  earStyle: 'round',
  
  eyeStyle: 'sparkle',
  eyelashesStyle: 'classic',
  eyeColor: '#0077b6',
  eyebrowStyle: 'neutral',
  eyeSize: 1.0,
  eyeSpacing: 35,
  eyeYOffset: 0,
  
  mouthStyle: 'smile',
  mouthYOffset: 0,
  mouthSize: 1.0,
  noseStyle: 'dot',
  noseYOffset: 0,
  blushIntensity: 0.5,
  faceAccessory: 'none',
  
  bangsStyle: 'straight',
  backHairStyle: 'short',
  hairColor: '#ffd166',
  hairAccentColor: '#ffb703',
  hairSize: 1.0,
  hairYOffset: 0,
  
  topStyle: 'hoodie',
  clothesColor1: '#003049',
  clothesColor2: '#fca311',
  bottomStyle: 'pants',
  shoesColor: '#1b1b1e',
  
  headwearStyle: 'none',
  headwearColor: '#3a0ca3',
  headwearPos: { x: 0, y: 0, scale: 1 },
  
  eyewearStyle: 'none',
  eyewearColor: '#ff007f',
  
  handItem: 'none',
  handItemColor: '#ef476f',
  
  backItem: 'none',
  tailStyle: 'none',
  
  bgStyle: 'circles',
  bgColor1: '#ffe5d9',
  bgColor2: '#ffd166',
};

export const CHIBI_PRESETS: ChibiConfig[] = [
  {
    ...DEFAULT_CHIBI,
    id: 'gatto_magico',
    name: '🐈 Gattino Stellare',
    gender: 'chubby',
    armPose: 'waving',
    skinColor: '#ffeee4',
    faceShape: 'chubby',
    earStyle: 'cat',
    eyeStyle: 'sparkle',
    eyelashesStyle: 'classic',
    eyeColor: '#7209b7',
    eyebrowStyle: 'happy',
    eyeSize: 1.1,
    eyeSpacing: 34,
    eyeYOffset: 0,
    mouthStyle: 'cat',
    blushIntensity: 0.8,
    faceAccessory: 'whiskers',
    bangsStyle: 'wispy',
    backHairStyle: 'twintails',
    hairColor: '#ff85a1',
    hairAccentColor: '#ff007f',
    topStyle: 'maid',
    clothesColor1: '#dec9e9',
    clothesColor2: '#1b1b1e',
    bottomStyle: 'frills',
    shoesColor: '#ff85a1',
    headwearStyle: 'cat_ears',
    headwearColor: '#ff85a1',
    headwearPos: { x: 0, y: 0, scale: 1 },
    handItem: 'balloon',
    handItemColor: '#ff007f',
    backItem: 'butterfly_wings',
    tailStyle: 'cat_tail',
    bgStyle: 'hearts',
    bgColor1: '#fec5bb',
    bgColor2: '#ffd166',
  },
  {
    ...DEFAULT_CHIBI,
    id: 'nerd_carino',
    name: '🤓 Nerd Genietto',
    gender: 'slender',
    armPose: 'neutral',
    skinColor: '#ffd6ba',
    faceShape: 'pointed',
    earStyle: 'round',
    eyeStyle: 'round',
    eyelashesStyle: 'none',
    eyeColor: '#212529',
    eyebrowStyle: 'neutral',
    eyeSize: 1.0,
    eyeSpacing: 35,
    eyeYOffset: -2,
    mouthStyle: 'smile',
    blushIntensity: 0.3,
    faceAccessory: 'band_aid',
    bangsStyle: 'side',
    backHairStyle: 'short',
    hairColor: '#6f4e37',
    hairAccentColor: '#ffd166',
    topStyle: 'shirt',
    clothesColor1: '#4a4e69',
    clothesColor2: '#003049',
    bottomStyle: 'pants',
    shoesColor: '#1b1b1e',
    eyewearStyle: 'round',
    handItem: 'wand',
    backItem: 'none',
    tailStyle: 'none',
    bgStyle: 'grid',
    bgColor1: '#d8e2dc',
    bgColor2: '#0077b6',
  },
  {
    ...DEFAULT_CHIBI,
    id: 'principe_demone',
    name: '😈 Piccolo Demone',
    gender: 'muscular',
    armPose: 'hips',
    skinColor: '#ffd6ba',
    faceShape: 'square',
    earStyle: 'elf',
    eyeStyle: 'cool',
    eyelashesStyle: 'none',
    eyeColor: '#d90429',
    eyebrowStyle: 'angry',
    eyeSize: 0.95,
    eyeSpacing: 37,
    eyeYOffset: 2,
    mouthStyle: 'tongue',
    blushIntensity: 0.6,
    faceAccessory: 'none',
    bangsStyle: 'spiky',
    backHairStyle: 'spiky',
    hairColor: '#1a1a1a',
    hairAccentColor: '#d90429',
    topStyle: 'armor',
    clothesColor1: '#1b1b1e',
    clothesColor2: '#d90429',
    bottomStyle: 'pants',
    shoesColor: '#1c1c1f',
    headwearStyle: 'horns',
    headwearColor: '#d90429',
    headwearPos: { x: 0, y: 0, scale: 1 },
    handItem: 'pet',
    handItemColor: '#ffffff',
    backItem: 'demon_wings',
    tailStyle: 'devil_tail',
    bgStyle: 'stars',
    bgColor1: '#2b2d42',
    bgColor2: '#d90429',
  },
  {
    ...DEFAULT_CHIBI,
    id: 'fragolina_baby',
    name: '🍼 Neonata Fragola',
    gender: 'baby_suit',
    armPose: 'holding',
    skinColor: '#ffeee4',
    faceShape: 'round',
    earStyle: 'bear',
    eyeStyle: 'sleeping',
    eyelashesStyle: 'classic',
    eyeColor: '#9c6644',
    eyebrowStyle: 'neutral',
    eyeSize: 1.0,
    eyeSpacing: 36,
    eyeYOffset: 0,
    mouthStyle: 'blush',
    blushIntensity: 0.9,
    faceAccessory: 'blush_heart',
    bangsStyle: 'curly',
    backHairStyle: 'none',
    hairColor: '#ffd166',
    topStyle: 'sweater',
    clothesColor1: '#fec5bb',
    clothesColor2: '#ffffff',
    shoesColor: '#ff85a1',
    headwearStyle: 'bear_beanie',
    headwearColor: '#fec5bb',
    headwearPos: { x: 0, y: 0, scale: 1.05 },
    handItem: 'icecream',
    handItemColor: '#ff85a1',
    backItem: 'none',
    tailStyle: 'bunny_tail',
    bgStyle: 'circles',
    bgColor1: '#ffe5d9',
    bgColor2: '#ff85a1',
  },
  {
    ...DEFAULT_CHIBI,
    id: 'angeli_custodi',
    name: '😇 Angioletto Custode',
    gender: 'slender',
    armPose: 'waving',
    skinColor: '#ffeee4',
    faceShape: 'pointed',
    earStyle: 'elf',
    eyeStyle: 'sparkle',
    eyelashesStyle: 'classic',
    eyeColor: '#00f5d4',
    eyebrowStyle: 'happy',
    eyeSize: 1.15,
    eyeSpacing: 33,
    eyeYOffset: -2,
    mouthStyle: 'surprise',
    blushIntensity: 0.7,
    faceAccessory: 'star_cheek',
    bangsStyle: 'wispy',
    backHairStyle: 'wavy',
    hairColor: '#e9ecef',
    hairAccentColor: '#4ea8de',
    topStyle: 'sweater',
    clothesColor1: '#dec9e9',
    clothesColor2: '#ffffff',
    bottomStyle: 'magical_dress',
    shoesColor: '#ffd166',
    headwearStyle: 'halo',
    headwearColor: '#ffe347',
    headwearPos: { x: 0, y: 0, scale: 1 },
    handItem: 'wand',
    backItem: 'angel_wings',
    tailStyle: 'none',
    bgStyle: 'stars',
    bgColor1: '#ebd9fc',
    bgColor2: '#ffe347',
  },
  {
    ...DEFAULT_CHIBI,
    id: 'skater_boy',
    name: '🛹 Ragazzo Skater',
    gender: 'base',
    armPose: 'waving',
    skinColor: '#ffd6ba',
    faceShape: 'pointed',
    earStyle: 'round',
    eyeStyle: 'cool',
    eyelashesStyle: 'none',
    eyeColor: '#0077b6',
    eyebrowStyle: 'neutral',
    eyeSize: 1.05,
    eyeSpacing: 35,
    eyeYOffset: 0,
    mouthStyle: 'smile',
    blushIntensity: 0.1,
    faceAccessory: 'band_aid',
    bangsStyle: 'side',
    backHairStyle: 'short',
    hairColor: '#ffd166',
    hairAccentColor: '#f77f00',
    topStyle: 'hoodie',
    clothesColor1: '#003049',
    clothesColor2: '#fca311',
    bottomStyle: 'pants',
    shoesColor: '#1b1b1e',
    headwearStyle: 'none',
    handItem: 'none',
    backItem: 'none',
    tailStyle: 'none',
    bgStyle: 'grid',
    bgColor1: '#d8e2dc',
    bgColor2: '#0077b6',
  }
];
